### ISSUE TITLE
P2P code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/weather-app#2]

**Comment by rammazzoti2000** [comment]
Great app, as always the design is very good. You could use an api to get random wallpaper based on the weather information whether is raining or is sunny, etc. [Giphy](https://giphy.com/) has free api's.

**Comment by dili021** [comment]
Nice work man, very nice separation of concerns.
Besides the object idea for images, here's a tip for writing less :

You can do this

![image](https://user-images.githubusercontent.com/55356496/89504486-5f44d900-d7c8-11ea-96b6-348be0c0f183.png)

Like this

![image](https://user-images.githubusercontent.com/55356496/89504615-9915df80-d7c8-11ea-8635-d4d1e7205ca9.png)

**Comment by nyatindopatrick** [comment]
Thank you for the feedback.
